// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgBossInfo.proto

package com.hailintang.client.protobuf.protoc;

public final class MsgBossInfoProto {
  private MsgBossInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ATTACKBOSS = 0;</code>
     */
    ATTACKBOSS(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ATTACKBOSS = 0;</code>
     */
    public static final int ATTACKBOSS_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return ATTACKBOSS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RequestType)
  }

  public interface RequestBossInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestBossInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    java.lang.String getRequestId();
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <pre>
     * 请求的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    int getUserId();

    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>string bossName = 3;</code>
     */
    java.lang.String getBossName();
    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>string bossName = 3;</code>
     */
    com.google.protobuf.ByteString
        getBossNameBytes();

    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType getType();

    /**
     * <code>string skillName = 5;</code>
     */
    java.lang.String getSkillName();
    /**
     * <code>string skillName = 5;</code>
     */
    com.google.protobuf.ByteString
        getSkillNameBytes();

    /**
     * <code>string mapName = 6;</code>
     */
    java.lang.String getMapName();
    /**
     * <code>string mapName = 6;</code>
     */
    com.google.protobuf.ByteString
        getMapNameBytes();
  }
  /**
   * Protobuf type {@code RequestBossInfo}
   */
  public  static final class RequestBossInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestBossInfo)
      RequestBossInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestBossInfo.newBuilder() to construct.
    private RequestBossInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestBossInfo() {
      requestId_ = "";
      bossName_ = "";
      type_ = 0;
      skillName_ = "";
      mapName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestBossInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 16: {

              userId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              bossName_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              skillName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              mapName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.internal_static_RequestBossInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.internal_static_RequestBossInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo.class, com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestId_;
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <pre>
     * 请求的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int BOSSNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object bossName_;
    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>string bossName = 3;</code>
     */
    public java.lang.String getBossName() {
      java.lang.Object ref = bossName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bossName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>string bossName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBossNameBytes() {
      java.lang.Object ref = bossName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bossName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    public com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType getType() {
      @SuppressWarnings("deprecation")
      com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType.valueOf(type_);
      return result == null ? com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType.UNRECOGNIZED : result;
    }

    public static final int SKILLNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object skillName_;
    /**
     * <code>string skillName = 5;</code>
     */
    public java.lang.String getSkillName() {
      java.lang.Object ref = skillName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skillName_ = s;
        return s;
      }
    }
    /**
     * <code>string skillName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSkillNameBytes() {
      java.lang.Object ref = skillName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skillName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAPNAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object mapName_;
    /**
     * <code>string mapName = 6;</code>
     */
    public java.lang.String getMapName() {
      java.lang.Object ref = mapName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mapName_ = s;
        return s;
      }
    }
    /**
     * <code>string mapName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMapNameBytes() {
      java.lang.Object ref = mapName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mapName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (userId_ != 0) {
        output.writeInt32(2, userId_);
      }
      if (!getBossNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bossName_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType.ATTACKBOSS.getNumber()) {
        output.writeEnum(4, type_);
      }
      if (!getSkillNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, skillName_);
      }
      if (!getMapNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, mapName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (!getBossNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bossName_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType.ATTACKBOSS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (!getSkillNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, skillName_);
      }
      if (!getMapNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, mapName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo)) {
        return super.equals(obj);
      }
      com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo other = (com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo) obj;

      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getBossName()
          .equals(other.getBossName())) return false;
      if (type_ != other.type_) return false;
      if (!getSkillName()
          .equals(other.getSkillName())) return false;
      if (!getMapName()
          .equals(other.getMapName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + BOSSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getBossName().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SKILLNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSkillName().hashCode();
      hash = (37 * hash) + MAPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMapName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestBossInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestBossInfo)
        com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.internal_static_RequestBossInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.internal_static_RequestBossInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo.class, com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo.Builder.class);
      }

      // Construct using com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = "";

        userId_ = 0;

        bossName_ = "";

        type_ = 0;

        skillName_ = "";

        mapName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.internal_static_RequestBossInfo_descriptor;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo getDefaultInstanceForType() {
        return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo build() {
        com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo buildPartial() {
        com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo result = new com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo(this);
        result.requestId_ = requestId_;
        result.userId_ = userId_;
        result.bossName_ = bossName_;
        result.type_ = type_;
        result.skillName_ = skillName_;
        result.mapName_ = mapName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo) {
          return mergeFrom((com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo other) {
        if (other == com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getBossName().isEmpty()) {
          bossName_ = other.bossName_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getSkillName().isEmpty()) {
          skillName_ = other.skillName_;
          onChanged();
        }
        if (!other.getMapName().isEmpty()) {
          mapName_ = other.mapName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestId_ = value;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       * 请求的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 请求的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object bossName_ = "";
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>string bossName = 3;</code>
       */
      public java.lang.String getBossName() {
        java.lang.Object ref = bossName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bossName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>string bossName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBossNameBytes() {
        java.lang.Object ref = bossName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bossName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>string bossName = 3;</code>
       */
      public Builder setBossName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bossName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>string bossName = 3;</code>
       */
      public Builder clearBossName() {
        
        bossName_ = getDefaultInstance().getBossName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>string bossName = 3;</code>
       */
      public Builder setBossNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bossName_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType getType() {
        @SuppressWarnings("deprecation")
        com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType.valueOf(type_);
        return result == null ? com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder setType(com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object skillName_ = "";
      /**
       * <code>string skillName = 5;</code>
       */
      public java.lang.String getSkillName() {
        java.lang.Object ref = skillName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          skillName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string skillName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSkillNameBytes() {
        java.lang.Object ref = skillName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          skillName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string skillName = 5;</code>
       */
      public Builder setSkillName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        skillName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string skillName = 5;</code>
       */
      public Builder clearSkillName() {
        
        skillName_ = getDefaultInstance().getSkillName();
        onChanged();
        return this;
      }
      /**
       * <code>string skillName = 5;</code>
       */
      public Builder setSkillNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        skillName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mapName_ = "";
      /**
       * <code>string mapName = 6;</code>
       */
      public java.lang.String getMapName() {
        java.lang.Object ref = mapName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mapName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mapName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMapNameBytes() {
        java.lang.Object ref = mapName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mapName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mapName = 6;</code>
       */
      public Builder setMapName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mapName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mapName = 6;</code>
       */
      public Builder clearMapName() {
        
        mapName_ = getDefaultInstance().getMapName();
        onChanged();
        return this;
      }
      /**
       * <code>string mapName = 6;</code>
       */
      public Builder setMapNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mapName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestBossInfo)
    }

    // @@protoc_insertion_point(class_scope:RequestBossInfo)
    private static final com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo();
    }

    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestBossInfo>
        PARSER = new com.google.protobuf.AbstractParser<RequestBossInfo>() {
      @java.lang.Override
      public RequestBossInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestBossInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestBossInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestBossInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestBossInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseBossInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseBossInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 返回结果
     * </pre>
     *
     * <code>int32 result = 1;</code>
     */
    int getResult();

    /**
     * <pre>
     * 返回的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    int getUserId();

    /**
     * <pre>
     * 返回内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 返回内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType getType();

    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    boolean hasRole();
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    com.hailintang.client.protobuf.protoc.RoleProto.Role getRole();
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder getRoleOrBuilder();
  }
  /**
   * Protobuf type {@code ResponseBossInfo}
   */
  public  static final class ResponseBossInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseBossInfo)
      ResponseBossInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseBossInfo.newBuilder() to construct.
    private ResponseBossInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseBossInfo() {
      content_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseBossInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              result_ = input.readInt32();
              break;
            }
            case 16: {

              userId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 42: {
              com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder subBuilder = null;
              if (role_ != null) {
                subBuilder = role_.toBuilder();
              }
              role_ = input.readMessage(com.hailintang.client.protobuf.protoc.RoleProto.Role.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(role_);
                role_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.internal_static_ResponseBossInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.internal_static_ResponseBossInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo.class, com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <pre>
     * 返回结果
     * </pre>
     *
     * <code>int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <pre>
     * 返回的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 返回内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 返回内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    public com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType getType() {
      @SuppressWarnings("deprecation")
      com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType.valueOf(type_);
      return result == null ? com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType.UNRECOGNIZED : result;
    }

    public static final int ROLE_FIELD_NUMBER = 5;
    private com.hailintang.client.protobuf.protoc.RoleProto.Role role_;
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    public boolean hasRole() {
      return role_ != null;
    }
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    public com.hailintang.client.protobuf.protoc.RoleProto.Role getRole() {
      return role_ == null ? com.hailintang.client.protobuf.protoc.RoleProto.Role.getDefaultInstance() : role_;
    }
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    public com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder getRoleOrBuilder() {
      return getRole();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeInt32(1, result_);
      }
      if (userId_ != 0) {
        output.writeInt32(2, userId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType.ATTACKBOSS.getNumber()) {
        output.writeEnum(4, type_);
      }
      if (role_ != null) {
        output.writeMessage(5, getRole());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType.ATTACKBOSS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (role_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getRole());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo)) {
        return super.equals(obj);
      }
      com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo other = (com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo) obj;

      if (getResult()
          != other.getResult()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (type_ != other.type_) return false;
      if (hasRole() != other.hasRole()) return false;
      if (hasRole()) {
        if (!getRole()
            .equals(other.getRole())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasRole()) {
        hash = (37 * hash) + ROLE_FIELD_NUMBER;
        hash = (53 * hash) + getRole().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseBossInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseBossInfo)
        com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.internal_static_ResponseBossInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.internal_static_ResponseBossInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo.class, com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo.Builder.class);
      }

      // Construct using com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        userId_ = 0;

        content_ = "";

        type_ = 0;

        if (roleBuilder_ == null) {
          role_ = null;
        } else {
          role_ = null;
          roleBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.internal_static_ResponseBossInfo_descriptor;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo getDefaultInstanceForType() {
        return com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo build() {
        com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo buildPartial() {
        com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo result = new com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo(this);
        result.result_ = result_;
        result.userId_ = userId_;
        result.content_ = content_;
        result.type_ = type_;
        if (roleBuilder_ == null) {
          result.role_ = role_;
        } else {
          result.role_ = roleBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo) {
          return mergeFrom((com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo other) {
        if (other == com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasRole()) {
          mergeRole(other.getRole());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ ;
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       * 返回的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 返回的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType getType() {
        @SuppressWarnings("deprecation")
        com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType.valueOf(type_);
        return result == null ? com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder setType(com.hailintang.client.protobuf.protoc.MsgBossInfoProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.hailintang.client.protobuf.protoc.RoleProto.Role role_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hailintang.client.protobuf.protoc.RoleProto.Role, com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder, com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder> roleBuilder_;
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public boolean hasRole() {
        return roleBuilder_ != null || role_ != null;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.RoleProto.Role getRole() {
        if (roleBuilder_ == null) {
          return role_ == null ? com.hailintang.client.protobuf.protoc.RoleProto.Role.getDefaultInstance() : role_;
        } else {
          return roleBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder setRole(com.hailintang.client.protobuf.protoc.RoleProto.Role value) {
        if (roleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          role_ = value;
          onChanged();
        } else {
          roleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder setRole(
          com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder builderForValue) {
        if (roleBuilder_ == null) {
          role_ = builderForValue.build();
          onChanged();
        } else {
          roleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder mergeRole(com.hailintang.client.protobuf.protoc.RoleProto.Role value) {
        if (roleBuilder_ == null) {
          if (role_ != null) {
            role_ =
              com.hailintang.client.protobuf.protoc.RoleProto.Role.newBuilder(role_).mergeFrom(value).buildPartial();
          } else {
            role_ = value;
          }
          onChanged();
        } else {
          roleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder clearRole() {
        if (roleBuilder_ == null) {
          role_ = null;
          onChanged();
        } else {
          role_ = null;
          roleBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder getRoleBuilder() {
        
        onChanged();
        return getRoleFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder getRoleOrBuilder() {
        if (roleBuilder_ != null) {
          return roleBuilder_.getMessageOrBuilder();
        } else {
          return role_ == null ?
              com.hailintang.client.protobuf.protoc.RoleProto.Role.getDefaultInstance() : role_;
        }
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hailintang.client.protobuf.protoc.RoleProto.Role, com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder, com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder> 
          getRoleFieldBuilder() {
        if (roleBuilder_ == null) {
          roleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.hailintang.client.protobuf.protoc.RoleProto.Role, com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder, com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder>(
                  getRole(),
                  getParentForChildren(),
                  isClean());
          role_ = null;
        }
        return roleBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseBossInfo)
    }

    // @@protoc_insertion_point(class_scope:ResponseBossInfo)
    private static final com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo();
    }

    public static com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseBossInfo>
        PARSER = new com.google.protobuf.AbstractParser<ResponseBossInfo>() {
      @java.lang.Override
      public ResponseBossInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseBossInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseBossInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseBossInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hailintang.client.protobuf.protoc.MsgBossInfoProto.ResponseBossInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestBossInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestBossInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseBossInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseBossInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MsgBossInfo.proto\032\nRole.proto\"\206\001\n\017Requ" +
      "estBossInfo\022\021\n\trequestId\030\001 \001(\t\022\016\n\006userId" +
      "\030\002 \001(\005\022\020\n\010bossName\030\003 \001(\t\022\032\n\004type\030\004 \001(\0162\014" +
      ".RequestType\022\021\n\tskillName\030\005 \001(\t\022\017\n\007mapNa" +
      "me\030\006 \001(\t\"t\n\020ResponseBossInfo\022\016\n\006result\030\001" +
      " \001(\005\022\016\n\006userId\030\002 \001(\005\022\017\n\007content\030\003 \001(\t\022\032\n" +
      "\004type\030\004 \001(\0162\014.RequestType\022\023\n\004role\030\005 \001(\0132" +
      "\005.Role*\035\n\013RequestType\022\016\n\nATTACKBOSS\020\000B9\n" +
      "%com.hailintang.client.protobuf.protocB\020" +
      "MsgBossInfoProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hailintang.client.protobuf.protoc.RoleProto.getDescriptor(),
        }, assigner);
    internal_static_RequestBossInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestBossInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestBossInfo_descriptor,
        new java.lang.String[] { "RequestId", "UserId", "BossName", "Type", "SkillName", "MapName", });
    internal_static_ResponseBossInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseBossInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseBossInfo_descriptor,
        new java.lang.String[] { "Result", "UserId", "Content", "Type", "Role", });
    com.hailintang.client.protobuf.protoc.RoleProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
