// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgGangInfo.proto

package com.hailintang.client.protobuf.protoc;

public final class MsgGangInfoProto {
  private MsgGangInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CREATEGANG = 0;</code>
     */
    CREATEGANG(0),
    /**
     * <code>JOINGANG = 1;</code>
     */
    JOINGANG(1),
    /**
     * <code>DISMISSGANG = 2;</code>
     */
    DISMISSGANG(2),
    /**
     * <code>DONATEMONEY = 3;</code>
     */
    DONATEMONEY(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CREATEGANG = 0;</code>
     */
    public static final int CREATEGANG_VALUE = 0;
    /**
     * <code>JOINGANG = 1;</code>
     */
    public static final int JOINGANG_VALUE = 1;
    /**
     * <code>DISMISSGANG = 2;</code>
     */
    public static final int DISMISSGANG_VALUE = 2;
    /**
     * <code>DONATEMONEY = 3;</code>
     */
    public static final int DONATEMONEY_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return CREATEGANG;
        case 1: return JOINGANG;
        case 2: return DISMISSGANG;
        case 3: return DONATEMONEY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RequestType)
  }

  public interface RequestGangInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestGangInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    java.lang.String getRequestId();
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <pre>
     * 请求的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    int getUserId();

    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>string gangName = 3;</code>
     */
    java.lang.String getGangName();
    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>string gangName = 3;</code>
     */
    com.google.protobuf.ByteString
        getGangNameBytes();

    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType getType();

    /**
     * <code>string number = 5;</code>
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 5;</code>
     */
    com.google.protobuf.ByteString
        getNumberBytes();
  }
  /**
   * Protobuf type {@code RequestGangInfo}
   */
  public  static final class RequestGangInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestGangInfo)
      RequestGangInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestGangInfo.newBuilder() to construct.
    private RequestGangInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestGangInfo() {
      requestId_ = "";
      gangName_ = "";
      type_ = 0;
      number_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestGangInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 16: {

              userId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              gangName_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              number_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.internal_static_RequestGangInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.internal_static_RequestGangInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo.class, com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestId_;
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <pre>
     * 请求的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int GANGNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object gangName_;
    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>string gangName = 3;</code>
     */
    public java.lang.String getGangName() {
      java.lang.Object ref = gangName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gangName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>string gangName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGangNameBytes() {
      java.lang.Object ref = gangName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gangName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    public com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType getType() {
      @SuppressWarnings("deprecation")
      com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType.valueOf(type_);
      return result == null ? com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType.UNRECOGNIZED : result;
    }

    public static final int NUMBER_FIELD_NUMBER = 5;
    private volatile java.lang.Object number_;
    /**
     * <code>string number = 5;</code>
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>string number = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (userId_ != 0) {
        output.writeInt32(2, userId_);
      }
      if (!getGangNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gangName_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType.CREATEGANG.getNumber()) {
        output.writeEnum(4, type_);
      }
      if (!getNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, number_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (!getGangNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gangName_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType.CREATEGANG.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (!getNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, number_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo)) {
        return super.equals(obj);
      }
      com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo other = (com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo) obj;

      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getGangName()
          .equals(other.getGangName())) return false;
      if (type_ != other.type_) return false;
      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + GANGNAME_FIELD_NUMBER;
      hash = (53 * hash) + getGangName().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestGangInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestGangInfo)
        com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.internal_static_RequestGangInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.internal_static_RequestGangInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo.class, com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo.Builder.class);
      }

      // Construct using com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = "";

        userId_ = 0;

        gangName_ = "";

        type_ = 0;

        number_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.internal_static_RequestGangInfo_descriptor;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo getDefaultInstanceForType() {
        return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo build() {
        com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo buildPartial() {
        com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo result = new com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo(this);
        result.requestId_ = requestId_;
        result.userId_ = userId_;
        result.gangName_ = gangName_;
        result.type_ = type_;
        result.number_ = number_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo) {
          return mergeFrom((com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo other) {
        if (other == com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getGangName().isEmpty()) {
          gangName_ = other.gangName_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestId_ = value;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       * 请求的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 请求的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object gangName_ = "";
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>string gangName = 3;</code>
       */
      public java.lang.String getGangName() {
        java.lang.Object ref = gangName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gangName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>string gangName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGangNameBytes() {
        java.lang.Object ref = gangName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gangName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>string gangName = 3;</code>
       */
      public Builder setGangName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gangName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>string gangName = 3;</code>
       */
      public Builder clearGangName() {
        
        gangName_ = getDefaultInstance().getGangName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>string gangName = 3;</code>
       */
      public Builder setGangNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gangName_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType getType() {
        @SuppressWarnings("deprecation")
        com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType.valueOf(type_);
        return result == null ? com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder setType(com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <code>string number = 5;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string number = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string number = 5;</code>
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string number = 5;</code>
       */
      public Builder clearNumber() {
        
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string number = 5;</code>
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        number_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestGangInfo)
    }

    // @@protoc_insertion_point(class_scope:RequestGangInfo)
    private static final com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo();
    }

    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestGangInfo>
        PARSER = new com.google.protobuf.AbstractParser<RequestGangInfo>() {
      @java.lang.Override
      public RequestGangInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestGangInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestGangInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestGangInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestGangInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseGangInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseGangInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 返回结果
     * </pre>
     *
     * <code>int32 result = 1;</code>
     */
    int getResult();

    /**
     * <pre>
     * 返回的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    int getUserId();

    /**
     * <pre>
     * 返回内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 返回内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType getType();

    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    boolean hasRole();
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    com.hailintang.client.protobuf.protoc.RoleProto.Role getRole();
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder getRoleOrBuilder();
  }
  /**
   * Protobuf type {@code ResponseGangInfo}
   */
  public  static final class ResponseGangInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseGangInfo)
      ResponseGangInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseGangInfo.newBuilder() to construct.
    private ResponseGangInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseGangInfo() {
      content_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseGangInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              result_ = input.readInt32();
              break;
            }
            case 16: {

              userId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 42: {
              com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder subBuilder = null;
              if (role_ != null) {
                subBuilder = role_.toBuilder();
              }
              role_ = input.readMessage(com.hailintang.client.protobuf.protoc.RoleProto.Role.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(role_);
                role_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.internal_static_ResponseGangInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.internal_static_ResponseGangInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo.class, com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <pre>
     * 返回结果
     * </pre>
     *
     * <code>int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <pre>
     * 返回的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 返回内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 返回内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    public com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType getType() {
      @SuppressWarnings("deprecation")
      com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType.valueOf(type_);
      return result == null ? com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType.UNRECOGNIZED : result;
    }

    public static final int ROLE_FIELD_NUMBER = 5;
    private com.hailintang.client.protobuf.protoc.RoleProto.Role role_;
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    public boolean hasRole() {
      return role_ != null;
    }
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    public com.hailintang.client.protobuf.protoc.RoleProto.Role getRole() {
      return role_ == null ? com.hailintang.client.protobuf.protoc.RoleProto.Role.getDefaultInstance() : role_;
    }
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    public com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder getRoleOrBuilder() {
      return getRole();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeInt32(1, result_);
      }
      if (userId_ != 0) {
        output.writeInt32(2, userId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType.CREATEGANG.getNumber()) {
        output.writeEnum(4, type_);
      }
      if (role_ != null) {
        output.writeMessage(5, getRole());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType.CREATEGANG.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (role_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getRole());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo)) {
        return super.equals(obj);
      }
      com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo other = (com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo) obj;

      if (getResult()
          != other.getResult()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (type_ != other.type_) return false;
      if (hasRole() != other.hasRole()) return false;
      if (hasRole()) {
        if (!getRole()
            .equals(other.getRole())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasRole()) {
        hash = (37 * hash) + ROLE_FIELD_NUMBER;
        hash = (53 * hash) + getRole().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseGangInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseGangInfo)
        com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.internal_static_ResponseGangInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.internal_static_ResponseGangInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo.class, com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo.Builder.class);
      }

      // Construct using com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        userId_ = 0;

        content_ = "";

        type_ = 0;

        if (roleBuilder_ == null) {
          role_ = null;
        } else {
          role_ = null;
          roleBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.internal_static_ResponseGangInfo_descriptor;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo getDefaultInstanceForType() {
        return com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo build() {
        com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo buildPartial() {
        com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo result = new com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo(this);
        result.result_ = result_;
        result.userId_ = userId_;
        result.content_ = content_;
        result.type_ = type_;
        if (roleBuilder_ == null) {
          result.role_ = role_;
        } else {
          result.role_ = roleBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo) {
          return mergeFrom((com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo other) {
        if (other == com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasRole()) {
          mergeRole(other.getRole());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ ;
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       * 返回的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 返回的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType getType() {
        @SuppressWarnings("deprecation")
        com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType.valueOf(type_);
        return result == null ? com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder setType(com.hailintang.client.protobuf.protoc.MsgGangInfoProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.hailintang.client.protobuf.protoc.RoleProto.Role role_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hailintang.client.protobuf.protoc.RoleProto.Role, com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder, com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder> roleBuilder_;
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public boolean hasRole() {
        return roleBuilder_ != null || role_ != null;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.RoleProto.Role getRole() {
        if (roleBuilder_ == null) {
          return role_ == null ? com.hailintang.client.protobuf.protoc.RoleProto.Role.getDefaultInstance() : role_;
        } else {
          return roleBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder setRole(com.hailintang.client.protobuf.protoc.RoleProto.Role value) {
        if (roleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          role_ = value;
          onChanged();
        } else {
          roleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder setRole(
          com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder builderForValue) {
        if (roleBuilder_ == null) {
          role_ = builderForValue.build();
          onChanged();
        } else {
          roleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder mergeRole(com.hailintang.client.protobuf.protoc.RoleProto.Role value) {
        if (roleBuilder_ == null) {
          if (role_ != null) {
            role_ =
              com.hailintang.client.protobuf.protoc.RoleProto.Role.newBuilder(role_).mergeFrom(value).buildPartial();
          } else {
            role_ = value;
          }
          onChanged();
        } else {
          roleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder clearRole() {
        if (roleBuilder_ == null) {
          role_ = null;
          onChanged();
        } else {
          role_ = null;
          roleBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder getRoleBuilder() {
        
        onChanged();
        return getRoleFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder getRoleOrBuilder() {
        if (roleBuilder_ != null) {
          return roleBuilder_.getMessageOrBuilder();
        } else {
          return role_ == null ?
              com.hailintang.client.protobuf.protoc.RoleProto.Role.getDefaultInstance() : role_;
        }
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hailintang.client.protobuf.protoc.RoleProto.Role, com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder, com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder> 
          getRoleFieldBuilder() {
        if (roleBuilder_ == null) {
          roleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.hailintang.client.protobuf.protoc.RoleProto.Role, com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder, com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder>(
                  getRole(),
                  getParentForChildren(),
                  isClean());
          role_ = null;
        }
        return roleBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseGangInfo)
    }

    // @@protoc_insertion_point(class_scope:ResponseGangInfo)
    private static final com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo();
    }

    public static com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseGangInfo>
        PARSER = new com.google.protobuf.AbstractParser<ResponseGangInfo>() {
      @java.lang.Override
      public ResponseGangInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseGangInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseGangInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseGangInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hailintang.client.protobuf.protoc.MsgGangInfoProto.ResponseGangInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestGangInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestGangInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseGangInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseGangInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MsgGangInfo.proto\032\nRole.proto\"r\n\017Reque" +
      "stGangInfo\022\021\n\trequestId\030\001 \001(\t\022\016\n\006userId\030" +
      "\002 \001(\005\022\020\n\010gangName\030\003 \001(\t\022\032\n\004type\030\004 \001(\0162\014." +
      "RequestType\022\016\n\006number\030\005 \001(\t\"t\n\020ResponseG" +
      "angInfo\022\016\n\006result\030\001 \001(\005\022\016\n\006userId\030\002 \001(\005\022" +
      "\017\n\007content\030\003 \001(\t\022\032\n\004type\030\004 \001(\0162\014.Request" +
      "Type\022\023\n\004role\030\005 \001(\0132\005.Role*M\n\013RequestType" +
      "\022\016\n\nCREATEGANG\020\000\022\014\n\010JOINGANG\020\001\022\017\n\013DISMIS" +
      "SGANG\020\002\022\017\n\013DONATEMONEY\020\003B9\n%com.hailinta" +
      "ng.client.protobuf.protocB\020MsgGangInfoPr" +
      "otob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hailintang.client.protobuf.protoc.RoleProto.getDescriptor(),
        }, assigner);
    internal_static_RequestGangInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestGangInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestGangInfo_descriptor,
        new java.lang.String[] { "RequestId", "UserId", "GangName", "Type", "Number", });
    internal_static_ResponseGangInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseGangInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseGangInfo_descriptor,
        new java.lang.String[] { "Result", "UserId", "Content", "Type", "Role", });
    com.hailintang.client.protobuf.protoc.RoleProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
