// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgRankInfo.proto

package com.hailintang.client.protobuf.protoc;

public final class MsgRankInfoProto {
  private MsgRankInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>QUERYRANK = 0;</code>
     */
    QUERYRANK(0),
    /**
     * <code>INSERTRANK = 1;</code>
     */
    INSERTRANK(1),
    /**
     * <code>DELETERANK = 2;</code>
     */
    DELETERANK(2),
    /**
     * <code>UPDATERANK = 3;</code>
     */
    UPDATERANK(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>QUERYRANK = 0;</code>
     */
    public static final int QUERYRANK_VALUE = 0;
    /**
     * <code>INSERTRANK = 1;</code>
     */
    public static final int INSERTRANK_VALUE = 1;
    /**
     * <code>DELETERANK = 2;</code>
     */
    public static final int DELETERANK_VALUE = 2;
    /**
     * <code>UPDATERANK = 3;</code>
     */
    public static final int UPDATERANK_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return QUERYRANK;
        case 1: return INSERTRANK;
        case 2: return DELETERANK;
        case 3: return UPDATERANK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RequestType)
  }

  public interface RequestRankInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestRankInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    java.lang.String getRequestId();
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <pre>
     * 请求的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    int getUserId();

    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 3;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 3;</code>
     */
    com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType getType();
  }
  /**
   * Protobuf type {@code RequestRankInfo}
   */
  public  static final class RequestRankInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestRankInfo)
      RequestRankInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestRankInfo.newBuilder() to construct.
    private RequestRankInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestRankInfo() {
      requestId_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestRankInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 16: {

              userId_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.internal_static_RequestRankInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.internal_static_RequestRankInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo.class, com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestId_;
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <pre>
     * 请求的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 3;</code>
     */
    public com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType getType() {
      @SuppressWarnings("deprecation")
      com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType.valueOf(type_);
      return result == null ? com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (userId_ != 0) {
        output.writeInt32(2, userId_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType.QUERYRANK.getNumber()) {
        output.writeEnum(3, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType.QUERYRANK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo)) {
        return super.equals(obj);
      }
      com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo other = (com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo) obj;

      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestRankInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestRankInfo)
        com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.internal_static_RequestRankInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.internal_static_RequestRankInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo.class, com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo.Builder.class);
      }

      // Construct using com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = "";

        userId_ = 0;

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.internal_static_RequestRankInfo_descriptor;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo getDefaultInstanceForType() {
        return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo build() {
        com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo buildPartial() {
        com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo result = new com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo(this);
        result.requestId_ = requestId_;
        result.userId_ = userId_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo) {
          return mergeFrom((com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo other) {
        if (other == com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestId_ = value;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       * 请求的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 请求的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 3;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 3;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 3;</code>
       */
      public com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType getType() {
        @SuppressWarnings("deprecation")
        com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType.valueOf(type_);
        return result == null ? com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 3;</code>
       */
      public Builder setType(com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestRankInfo)
    }

    // @@protoc_insertion_point(class_scope:RequestRankInfo)
    private static final com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo();
    }

    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestRankInfo>
        PARSER = new com.google.protobuf.AbstractParser<RequestRankInfo>() {
      @java.lang.Override
      public RequestRankInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestRankInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestRankInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestRankInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestRankInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseRankInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseRankInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 返回结果
     * </pre>
     *
     * <code>int32 result = 1;</code>
     */
    int getResult();

    /**
     * <pre>
     * 返回的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    int getUserId();

    /**
     * <pre>
     * 返回内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 返回内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType getType();

    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    boolean hasRole();
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    com.hailintang.client.protobuf.protoc.RoleProto.Role getRole();
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder getRoleOrBuilder();
  }
  /**
   * Protobuf type {@code ResponseRankInfo}
   */
  public  static final class ResponseRankInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseRankInfo)
      ResponseRankInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseRankInfo.newBuilder() to construct.
    private ResponseRankInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseRankInfo() {
      content_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseRankInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              result_ = input.readInt32();
              break;
            }
            case 16: {

              userId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 42: {
              com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder subBuilder = null;
              if (role_ != null) {
                subBuilder = role_.toBuilder();
              }
              role_ = input.readMessage(com.hailintang.client.protobuf.protoc.RoleProto.Role.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(role_);
                role_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.internal_static_ResponseRankInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.internal_static_ResponseRankInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo.class, com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <pre>
     * 返回结果
     * </pre>
     *
     * <code>int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <pre>
     * 返回的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 返回内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 返回内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    public com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType getType() {
      @SuppressWarnings("deprecation")
      com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType.valueOf(type_);
      return result == null ? com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType.UNRECOGNIZED : result;
    }

    public static final int ROLE_FIELD_NUMBER = 5;
    private com.hailintang.client.protobuf.protoc.RoleProto.Role role_;
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    public boolean hasRole() {
      return role_ != null;
    }
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    public com.hailintang.client.protobuf.protoc.RoleProto.Role getRole() {
      return role_ == null ? com.hailintang.client.protobuf.protoc.RoleProto.Role.getDefaultInstance() : role_;
    }
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    public com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder getRoleOrBuilder() {
      return getRole();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeInt32(1, result_);
      }
      if (userId_ != 0) {
        output.writeInt32(2, userId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType.QUERYRANK.getNumber()) {
        output.writeEnum(4, type_);
      }
      if (role_ != null) {
        output.writeMessage(5, getRole());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType.QUERYRANK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (role_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getRole());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo)) {
        return super.equals(obj);
      }
      com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo other = (com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo) obj;

      if (getResult()
          != other.getResult()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (type_ != other.type_) return false;
      if (hasRole() != other.hasRole()) return false;
      if (hasRole()) {
        if (!getRole()
            .equals(other.getRole())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasRole()) {
        hash = (37 * hash) + ROLE_FIELD_NUMBER;
        hash = (53 * hash) + getRole().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseRankInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseRankInfo)
        com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.internal_static_ResponseRankInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.internal_static_ResponseRankInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo.class, com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo.Builder.class);
      }

      // Construct using com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        userId_ = 0;

        content_ = "";

        type_ = 0;

        if (roleBuilder_ == null) {
          role_ = null;
        } else {
          role_ = null;
          roleBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.internal_static_ResponseRankInfo_descriptor;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo getDefaultInstanceForType() {
        return com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo build() {
        com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo buildPartial() {
        com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo result = new com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo(this);
        result.result_ = result_;
        result.userId_ = userId_;
        result.content_ = content_;
        result.type_ = type_;
        if (roleBuilder_ == null) {
          result.role_ = role_;
        } else {
          result.role_ = roleBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo) {
          return mergeFrom((com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo other) {
        if (other == com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasRole()) {
          mergeRole(other.getRole());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ ;
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       * 返回的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 返回的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType getType() {
        @SuppressWarnings("deprecation")
        com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType.valueOf(type_);
        return result == null ? com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder setType(com.hailintang.client.protobuf.protoc.MsgRankInfoProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.hailintang.client.protobuf.protoc.RoleProto.Role role_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hailintang.client.protobuf.protoc.RoleProto.Role, com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder, com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder> roleBuilder_;
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public boolean hasRole() {
        return roleBuilder_ != null || role_ != null;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.RoleProto.Role getRole() {
        if (roleBuilder_ == null) {
          return role_ == null ? com.hailintang.client.protobuf.protoc.RoleProto.Role.getDefaultInstance() : role_;
        } else {
          return roleBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder setRole(com.hailintang.client.protobuf.protoc.RoleProto.Role value) {
        if (roleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          role_ = value;
          onChanged();
        } else {
          roleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder setRole(
          com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder builderForValue) {
        if (roleBuilder_ == null) {
          role_ = builderForValue.build();
          onChanged();
        } else {
          roleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder mergeRole(com.hailintang.client.protobuf.protoc.RoleProto.Role value) {
        if (roleBuilder_ == null) {
          if (role_ != null) {
            role_ =
              com.hailintang.client.protobuf.protoc.RoleProto.Role.newBuilder(role_).mergeFrom(value).buildPartial();
          } else {
            role_ = value;
          }
          onChanged();
        } else {
          roleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder clearRole() {
        if (roleBuilder_ == null) {
          role_ = null;
          onChanged();
        } else {
          role_ = null;
          roleBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder getRoleBuilder() {
        
        onChanged();
        return getRoleFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder getRoleOrBuilder() {
        if (roleBuilder_ != null) {
          return roleBuilder_.getMessageOrBuilder();
        } else {
          return role_ == null ?
              com.hailintang.client.protobuf.protoc.RoleProto.Role.getDefaultInstance() : role_;
        }
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hailintang.client.protobuf.protoc.RoleProto.Role, com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder, com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder> 
          getRoleFieldBuilder() {
        if (roleBuilder_ == null) {
          roleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.hailintang.client.protobuf.protoc.RoleProto.Role, com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder, com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder>(
                  getRole(),
                  getParentForChildren(),
                  isClean());
          role_ = null;
        }
        return roleBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseRankInfo)
    }

    // @@protoc_insertion_point(class_scope:ResponseRankInfo)
    private static final com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo();
    }

    public static com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseRankInfo>
        PARSER = new com.google.protobuf.AbstractParser<ResponseRankInfo>() {
      @java.lang.Override
      public ResponseRankInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseRankInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseRankInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseRankInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hailintang.client.protobuf.protoc.MsgRankInfoProto.ResponseRankInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestRankInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestRankInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseRankInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseRankInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MsgRankInfo.proto\032\nRole.proto\"P\n\017Reque" +
      "stRankInfo\022\021\n\trequestId\030\001 \001(\t\022\016\n\006userId\030" +
      "\002 \001(\005\022\032\n\004type\030\003 \001(\0162\014.RequestType\"t\n\020Res" +
      "ponseRankInfo\022\016\n\006result\030\001 \001(\005\022\016\n\006userId\030" +
      "\002 \001(\005\022\017\n\007content\030\003 \001(\t\022\032\n\004type\030\004 \001(\0162\014.R" +
      "equestType\022\023\n\004role\030\005 \001(\0132\005.Role*L\n\013Reque" +
      "stType\022\r\n\tQUERYRANK\020\000\022\016\n\nINSERTRANK\020\001\022\016\n" +
      "\nDELETERANK\020\002\022\016\n\nUPDATERANK\020\003B9\n%com.hai" +
      "lintang.client.protobuf.protocB\020MsgRankI" +
      "nfoProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hailintang.client.protobuf.protoc.RoleProto.getDescriptor(),
        }, assigner);
    internal_static_RequestRankInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestRankInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestRankInfo_descriptor,
        new java.lang.String[] { "RequestId", "UserId", "Type", });
    internal_static_ResponseRankInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseRankInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseRankInfo_descriptor,
        new java.lang.String[] { "Result", "UserId", "Content", "Type", "Role", });
    com.hailintang.client.protobuf.protoc.RoleProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
