// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgRoleInfo.proto

package com.hailintang.client.protobuf.protoc;

public final class MsgRoleInfoProto {
  private MsgRoleInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CHOOSEROLE = 0;</code>
     */
    CHOOSEROLE(0),
    /**
     * <code>ROLEINFO = 1;</code>
     */
    ROLEINFO(1),
    /**
     * <code>USEGOODS = 2;</code>
     */
    USEGOODS(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CHOOSEROLE = 0;</code>
     */
    public static final int CHOOSEROLE_VALUE = 0;
    /**
     * <code>ROLEINFO = 1;</code>
     */
    public static final int ROLEINFO_VALUE = 1;
    /**
     * <code>USEGOODS = 2;</code>
     */
    public static final int USEGOODS_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return CHOOSEROLE;
        case 1: return ROLEINFO;
        case 2: return USEGOODS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RequestType)
  }

  public interface RequestRoleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestRoleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    java.lang.String getRequestId();
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <pre>
     * 请求的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    int getUserId();

    /**
     * <code>string roleName = 3;</code>
     */
    java.lang.String getRoleName();
    /**
     * <code>string roleName = 3;</code>
     */
    com.google.protobuf.ByteString
        getRoleNameBytes();

    /**
     * <code>int32 occupationId = 4;</code>
     */
    int getOccupationId();

    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 5;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 5;</code>
     */
    com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType getType();

    /**
     * <code>string goodsName = 6;</code>
     */
    java.lang.String getGoodsName();
    /**
     * <code>string goodsName = 6;</code>
     */
    com.google.protobuf.ByteString
        getGoodsNameBytes();
  }
  /**
   * Protobuf type {@code RequestRoleInfo}
   */
  public  static final class RequestRoleInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestRoleInfo)
      RequestRoleInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestRoleInfo.newBuilder() to construct.
    private RequestRoleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestRoleInfo() {
      requestId_ = "";
      roleName_ = "";
      type_ = 0;
      goodsName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestRoleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 16: {

              userId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              roleName_ = s;
              break;
            }
            case 32: {

              occupationId_ = input.readInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              goodsName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.internal_static_RequestRoleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.internal_static_RequestRoleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo.class, com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestId_;
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求id
     * </pre>
     *
     * <code>string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <pre>
     * 请求的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int ROLENAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object roleName_;
    /**
     * <code>string roleName = 3;</code>
     */
    public java.lang.String getRoleName() {
      java.lang.Object ref = roleName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roleName_ = s;
        return s;
      }
    }
    /**
     * <code>string roleName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRoleNameBytes() {
      java.lang.Object ref = roleName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OCCUPATIONID_FIELD_NUMBER = 4;
    private int occupationId_;
    /**
     * <code>int32 occupationId = 4;</code>
     */
    public int getOccupationId() {
      return occupationId_;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 5;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 请求类型
     * </pre>
     *
     * <code>.RequestType type = 5;</code>
     */
    public com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType getType() {
      @SuppressWarnings("deprecation")
      com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType.valueOf(type_);
      return result == null ? com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType.UNRECOGNIZED : result;
    }

    public static final int GOODSNAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object goodsName_;
    /**
     * <code>string goodsName = 6;</code>
     */
    public java.lang.String getGoodsName() {
      java.lang.Object ref = goodsName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        goodsName_ = s;
        return s;
      }
    }
    /**
     * <code>string goodsName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGoodsNameBytes() {
      java.lang.Object ref = goodsName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        goodsName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (userId_ != 0) {
        output.writeInt32(2, userId_);
      }
      if (!getRoleNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, roleName_);
      }
      if (occupationId_ != 0) {
        output.writeInt32(4, occupationId_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType.CHOOSEROLE.getNumber()) {
        output.writeEnum(5, type_);
      }
      if (!getGoodsNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, goodsName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (!getRoleNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, roleName_);
      }
      if (occupationId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, occupationId_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType.CHOOSEROLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_);
      }
      if (!getGoodsNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, goodsName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo)) {
        return super.equals(obj);
      }
      com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo other = (com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo) obj;

      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getRoleName()
          .equals(other.getRoleName())) return false;
      if (getOccupationId()
          != other.getOccupationId()) return false;
      if (type_ != other.type_) return false;
      if (!getGoodsName()
          .equals(other.getGoodsName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + ROLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getRoleName().hashCode();
      hash = (37 * hash) + OCCUPATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getOccupationId();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + GOODSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getGoodsName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestRoleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestRoleInfo)
        com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.internal_static_RequestRoleInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.internal_static_RequestRoleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo.class, com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo.Builder.class);
      }

      // Construct using com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = "";

        userId_ = 0;

        roleName_ = "";

        occupationId_ = 0;

        type_ = 0;

        goodsName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.internal_static_RequestRoleInfo_descriptor;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo getDefaultInstanceForType() {
        return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo build() {
        com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo buildPartial() {
        com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo result = new com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo(this);
        result.requestId_ = requestId_;
        result.userId_ = userId_;
        result.roleName_ = roleName_;
        result.occupationId_ = occupationId_;
        result.type_ = type_;
        result.goodsName_ = goodsName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo) {
          return mergeFrom((com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo other) {
        if (other == com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getRoleName().isEmpty()) {
          roleName_ = other.roleName_;
          onChanged();
        }
        if (other.getOccupationId() != 0) {
          setOccupationId(other.getOccupationId());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getGoodsName().isEmpty()) {
          goodsName_ = other.goodsName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求id
       * </pre>
       *
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestId_ = value;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       * 请求的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 请求的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object roleName_ = "";
      /**
       * <code>string roleName = 3;</code>
       */
      public java.lang.String getRoleName() {
        java.lang.Object ref = roleName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roleName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string roleName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRoleNameBytes() {
        java.lang.Object ref = roleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string roleName = 3;</code>
       */
      public Builder setRoleName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roleName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string roleName = 3;</code>
       */
      public Builder clearRoleName() {
        
        roleName_ = getDefaultInstance().getRoleName();
        onChanged();
        return this;
      }
      /**
       * <code>string roleName = 3;</code>
       */
      public Builder setRoleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roleName_ = value;
        onChanged();
        return this;
      }

      private int occupationId_ ;
      /**
       * <code>int32 occupationId = 4;</code>
       */
      public int getOccupationId() {
        return occupationId_;
      }
      /**
       * <code>int32 occupationId = 4;</code>
       */
      public Builder setOccupationId(int value) {
        
        occupationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 occupationId = 4;</code>
       */
      public Builder clearOccupationId() {
        
        occupationId_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 5;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 5;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType getType() {
        @SuppressWarnings("deprecation")
        com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType.valueOf(type_);
        return result == null ? com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 5;</code>
       */
      public Builder setType(com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求类型
       * </pre>
       *
       * <code>.RequestType type = 5;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object goodsName_ = "";
      /**
       * <code>string goodsName = 6;</code>
       */
      public java.lang.String getGoodsName() {
        java.lang.Object ref = goodsName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          goodsName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string goodsName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getGoodsNameBytes() {
        java.lang.Object ref = goodsName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          goodsName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string goodsName = 6;</code>
       */
      public Builder setGoodsName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        goodsName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string goodsName = 6;</code>
       */
      public Builder clearGoodsName() {
        
        goodsName_ = getDefaultInstance().getGoodsName();
        onChanged();
        return this;
      }
      /**
       * <code>string goodsName = 6;</code>
       */
      public Builder setGoodsNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        goodsName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestRoleInfo)
    }

    // @@protoc_insertion_point(class_scope:RequestRoleInfo)
    private static final com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo();
    }

    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestRoleInfo>
        PARSER = new com.google.protobuf.AbstractParser<RequestRoleInfo>() {
      @java.lang.Override
      public RequestRoleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestRoleInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestRoleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestRoleInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestRoleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseRoleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseRoleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 返回结果
     * </pre>
     *
     * <code>int32 result = 1;</code>
     */
    int getResult();

    /**
     * <pre>
     * 返回的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    int getUserId();

    /**
     * <code>string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType getType();

    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    boolean hasRole();
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    com.hailintang.client.protobuf.protoc.RoleProto.Role getRole();
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder getRoleOrBuilder();
  }
  /**
   * Protobuf type {@code ResponseRoleInfo}
   */
  public  static final class ResponseRoleInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseRoleInfo)
      ResponseRoleInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseRoleInfo.newBuilder() to construct.
    private ResponseRoleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseRoleInfo() {
      content_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseRoleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              result_ = input.readInt32();
              break;
            }
            case 16: {

              userId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 42: {
              com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder subBuilder = null;
              if (role_ != null) {
                subBuilder = role_.toBuilder();
              }
              role_ = input.readMessage(com.hailintang.client.protobuf.protoc.RoleProto.Role.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(role_);
                role_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.internal_static_ResponseRoleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.internal_static_ResponseRoleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo.class, com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <pre>
     * 返回结果
     * </pre>
     *
     * <code>int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <pre>
     * 返回的uid
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 返回类型
     * </pre>
     *
     * <code>.RequestType type = 4;</code>
     */
    public com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType getType() {
      @SuppressWarnings("deprecation")
      com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType.valueOf(type_);
      return result == null ? com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType.UNRECOGNIZED : result;
    }

    public static final int ROLE_FIELD_NUMBER = 5;
    private com.hailintang.client.protobuf.protoc.RoleProto.Role role_;
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    public boolean hasRole() {
      return role_ != null;
    }
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    public com.hailintang.client.protobuf.protoc.RoleProto.Role getRole() {
      return role_ == null ? com.hailintang.client.protobuf.protoc.RoleProto.Role.getDefaultInstance() : role_;
    }
    /**
     * <pre>
     * 用户角色
     * </pre>
     *
     * <code>.Role role = 5;</code>
     */
    public com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder getRoleOrBuilder() {
      return getRole();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeInt32(1, result_);
      }
      if (userId_ != 0) {
        output.writeInt32(2, userId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType.CHOOSEROLE.getNumber()) {
        output.writeEnum(4, type_);
      }
      if (role_ != null) {
        output.writeMessage(5, getRole());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (type_ != com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType.CHOOSEROLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (role_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getRole());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo)) {
        return super.equals(obj);
      }
      com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo other = (com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo) obj;

      if (getResult()
          != other.getResult()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (type_ != other.type_) return false;
      if (hasRole() != other.hasRole()) return false;
      if (hasRole()) {
        if (!getRole()
            .equals(other.getRole())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasRole()) {
        hash = (37 * hash) + ROLE_FIELD_NUMBER;
        hash = (53 * hash) + getRole().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseRoleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseRoleInfo)
        com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.internal_static_ResponseRoleInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.internal_static_ResponseRoleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo.class, com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo.Builder.class);
      }

      // Construct using com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        userId_ = 0;

        content_ = "";

        type_ = 0;

        if (roleBuilder_ == null) {
          role_ = null;
        } else {
          role_ = null;
          roleBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.internal_static_ResponseRoleInfo_descriptor;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo getDefaultInstanceForType() {
        return com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo build() {
        com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo buildPartial() {
        com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo result = new com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo(this);
        result.result_ = result_;
        result.userId_ = userId_;
        result.content_ = content_;
        result.type_ = type_;
        if (roleBuilder_ == null) {
          result.role_ = role_;
        } else {
          result.role_ = roleBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo) {
          return mergeFrom((com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo other) {
        if (other == com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasRole()) {
          mergeRole(other.getRole());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ ;
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       * 返回的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 返回的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回的uid
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType getType() {
        @SuppressWarnings("deprecation")
        com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType result = com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType.valueOf(type_);
        return result == null ? com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder setType(com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回类型
       * </pre>
       *
       * <code>.RequestType type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.hailintang.client.protobuf.protoc.RoleProto.Role role_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hailintang.client.protobuf.protoc.RoleProto.Role, com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder, com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder> roleBuilder_;
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public boolean hasRole() {
        return roleBuilder_ != null || role_ != null;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.RoleProto.Role getRole() {
        if (roleBuilder_ == null) {
          return role_ == null ? com.hailintang.client.protobuf.protoc.RoleProto.Role.getDefaultInstance() : role_;
        } else {
          return roleBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder setRole(com.hailintang.client.protobuf.protoc.RoleProto.Role value) {
        if (roleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          role_ = value;
          onChanged();
        } else {
          roleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder setRole(
          com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder builderForValue) {
        if (roleBuilder_ == null) {
          role_ = builderForValue.build();
          onChanged();
        } else {
          roleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder mergeRole(com.hailintang.client.protobuf.protoc.RoleProto.Role value) {
        if (roleBuilder_ == null) {
          if (role_ != null) {
            role_ =
              com.hailintang.client.protobuf.protoc.RoleProto.Role.newBuilder(role_).mergeFrom(value).buildPartial();
          } else {
            role_ = value;
          }
          onChanged();
        } else {
          roleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public Builder clearRole() {
        if (roleBuilder_ == null) {
          role_ = null;
          onChanged();
        } else {
          role_ = null;
          roleBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder getRoleBuilder() {
        
        onChanged();
        return getRoleFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      public com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder getRoleOrBuilder() {
        if (roleBuilder_ != null) {
          return roleBuilder_.getMessageOrBuilder();
        } else {
          return role_ == null ?
              com.hailintang.client.protobuf.protoc.RoleProto.Role.getDefaultInstance() : role_;
        }
      }
      /**
       * <pre>
       * 用户角色
       * </pre>
       *
       * <code>.Role role = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hailintang.client.protobuf.protoc.RoleProto.Role, com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder, com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder> 
          getRoleFieldBuilder() {
        if (roleBuilder_ == null) {
          roleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.hailintang.client.protobuf.protoc.RoleProto.Role, com.hailintang.client.protobuf.protoc.RoleProto.Role.Builder, com.hailintang.client.protobuf.protoc.RoleProto.RoleOrBuilder>(
                  getRole(),
                  getParentForChildren(),
                  isClean());
          role_ = null;
        }
        return roleBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseRoleInfo)
    }

    // @@protoc_insertion_point(class_scope:ResponseRoleInfo)
    private static final com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo();
    }

    public static com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseRoleInfo>
        PARSER = new com.google.protobuf.AbstractParser<ResponseRoleInfo>() {
      @java.lang.Override
      public ResponseRoleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseRoleInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseRoleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseRoleInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hailintang.client.protobuf.protoc.MsgRoleInfoProto.ResponseRoleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestRoleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestRoleInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseRoleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseRoleInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MsgRoleInfo.proto\032\nRole.proto\"\213\001\n\017Requ" +
      "estRoleInfo\022\021\n\trequestId\030\001 \001(\t\022\016\n\006userId" +
      "\030\002 \001(\005\022\020\n\010roleName\030\003 \001(\t\022\024\n\014occupationId" +
      "\030\004 \001(\005\022\032\n\004type\030\005 \001(\0162\014.RequestType\022\021\n\tgo" +
      "odsName\030\006 \001(\t\"t\n\020ResponseRoleInfo\022\016\n\006res" +
      "ult\030\001 \001(\005\022\016\n\006userId\030\002 \001(\005\022\017\n\007content\030\003 \001" +
      "(\t\022\032\n\004type\030\004 \001(\0162\014.RequestType\022\023\n\004role\030\005" +
      " \001(\0132\005.Role*9\n\013RequestType\022\016\n\nCHOOSEROLE" +
      "\020\000\022\014\n\010ROLEINFO\020\001\022\014\n\010USEGOODS\020\002B9\n%com.ha" +
      "ilintang.client.protobuf.protocB\020MsgRole" +
      "InfoProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hailintang.client.protobuf.protoc.RoleProto.getDescriptor(),
        }, assigner);
    internal_static_RequestRoleInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestRoleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestRoleInfo_descriptor,
        new java.lang.String[] { "RequestId", "UserId", "RoleName", "OccupationId", "Type", "GoodsName", });
    internal_static_ResponseRoleInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseRoleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseRoleInfo_descriptor,
        new java.lang.String[] { "Result", "UserId", "Content", "Type", "Role", });
    com.hailintang.client.protobuf.protoc.RoleProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
